remote_theme: coursweb/jk-theme
title: Outils
description: Les outils de la programmation web.
lang: fr-FR
# Chapters : top navigation
chapters:
 - title: Cours-web
   url: https://cours-web.ch/
 - title: Outils
   url: https://cours-web.ch/outils/

# Footer content
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2017–2021</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/coursweb/outils">Lien Github</a></li></ul>